Repository briannededeugd/tumimundo, pull requests merged in 2024-06, with the labels that each got.

#60 FEAT: FETCH from Directus and display in page, now trying to POST
  tumi-mundo/.example.env
  tumi-mundo/package-lock.json
  tumi-mundo/package.json
  tumi-mundo/src/routes/server/+page.server.js
  tumi-mundo/src/routes/server/+page.svelte
  tumi-mundo/static/lib/utils/fetchApi.js
Labels: pls help •᷄ࡇ•᷅, SOS 🛟, technical issue 🏗

#62 FIX/STYLE: d3 graph x- and y-axis
  tumi-mundo/src/components/LineChart.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: adorable :sparkles:

#64 STYLE/FEAT: New frontend design, card moves with audio
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/statistics/+page.svelte
  tumi-mundo/static/lib/images/background/a.svg
  tumi-mundo/static/lib/images/background/e.svg
  tumi-mundo/static/lib/images/background/i.svg
  tumi-mundo/static/lib/images/background/o.svg
  tumi-mundo/static/lib/images/background/u.svg
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, feat 𓃀, adorable :sparkles:

#65 FEAT/ADD: Added Spanish audio, and succesful POST form to Directus! Also merging branches.
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/server/+page.server.js
  tumi-mundo/src/routes/server/+page.svelte
  tumi-mundo/static/lib/audios/ES-HF-audio.m4a
  tumi-mundo/static/lib/utils/fetchApi.js
Labels: hhahahah (✿◠‿◠), feat 𓃀, adorable :sparkles:

#66 FEAT: Data POST+FETCH dynamically and compact
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/onboarding/+page.svelte
  tumi-mundo/src/routes/server/+page.server.js
  tumi-mundo/static/lib/styles/style.css
  tumi-mundo/static/lib/utils/fetchApi.js
Labels: skill issue ⋆ᶿ̴̤᷇ ˒̫ ᶿ̴̤᷆⋆, feat 𓃀

#69 TEST: Fix attention test bg-letter source
  tumi-mundo/src/routes/attentiontest/+page.svelte
Labels: unforch ¯\_(ツ)_/¯

#70 FEATURE: customization
  .vscode/settings.json
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/customization/+page.svelte
  tumi-mundo/src/routes/stores.js
  tumi-mundo/static/lib/audios/LF-list1.wav
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, adorable :sparkles:

#71 FIX/ADD: Send data to directus, move utils to src, add helper functions, add ES audio
  tumi-mundo/src/routes/attentiontest/+page.server.js
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/utils/fetchApi.js
  tumi-mundo/src/utils/fetchTest.js
Labels: hhahahah (✿◠‿◠), feat 𓃀, adorable :sparkles:

#72 STYLE: fix contrast issues on general pages + contrast fix start on /statistics
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/src/routes/server/+page.server.js
  tumi-mundo/src/routes/statistics/+page.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, hhahahah (✿◠‿◠), feat 𓃀, adorable :sparkles:

#79 FEAT: Toggle motion in attention test
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/stores.js
Labels: hhahahah (✿◠‿◠), feat 𓃀

#80 Tumi customization
  tumi-mundo/src/routes/customization/+page.svelte
  tumi-mundo/src/routes/stores.js
Labels: fix 🔫, adorable :sparkles:

#81 FIX/README: Finish README, add privacy statement with styling
  README.MD
  tumi-mundo/src/routes/onboarding/+page.svelte
Labels: style ₊⊹⋆⁺, fix 🔫, receipts 💅📸, adorable :sparkles:
