Repository briannededeugd/tumimundo, pull requests merged in 2024-05, with the labels that each got.

#3 STYLE/ADD: Added variable for font-weight and CSS reset, added .gitignore in root
  .gitignore
  tumi-mundo/src/lib/styles/style.css
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/static/lib/fonts/Poppins/OFL.txt
  tumi-mundo/static/lib/fonts/Poppins/Poppins-Regular.ttf
  tumi-mundo/static/lib/fonts/Poppins/Poppins-SemiBold.ttf
  tumi-mundo/static/lib/index.js
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺

#7 README/FIX: Trying to fix indentation again..
  README.MD
Labels: hhahahah (✿◠‿◠), fix 🔫, receipts 💅📸, technical issue 🏗

#8 STYLE: Start adding content from prototype (home/start page)
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, receipts 💅📸

#9 ADD: New route and script
  tumi-mundo/src/routes/test/+page.svelte
  tumi-mundo/static/lib/scripts/index.js
Labels: pls help •᷄ࡇ•᷅, SOS 🛟, technical issue 🏗, i'm s̴͓̙͓͑͆̚a̵͙͔̦̒͌͝d̵̫͔̟̿̓͆

#10 STYLE/ADD: Testing overview page style / privacy claim
  tumi-mundo/src/app.html
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, feat 𓃀

#11 FEAT: Added in pico&lploc&camvas.js libraries
  tumi-mundo/src/routes/test/+page.svelte
Labels: feat 𓃀

#12 ADD: concurrently and nodemon npm pkg
  tumi-mundo/package-lock.json
  tumi-mundo/package.json
Labels: fix 🔫

#14 ADD/STYLE: New customization page, edit CSS variable names
  tumi-mundo/src/routes/customization/+page.svelte
  tumi-mundo/src/routes/test/+page.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, receipts 💅📸

#15 README: Add intro and fix styling
  README.MD
Labels: fix 🔫, receipts 💅📸

#17 ADD: Test further section styling
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/static/lib/images/universiteit-leiden-logo.png
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, feat 𓃀

#19 FEAT: Test-file for attention test logs baby's attention
  tumi-mundo/src/routes/attentiontest/+page.svelte
Labels: style ₊⊹⋆⁺, feat 𓃀

#20 ADD: Link different pages
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/src/routes/customization/+page.svelte
Labels: feat 𓃀

#24 ADD: customization styling and Live Share config
  tumi-mundo/package.json
  tumi-mundo/src/app.html
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/src/routes/customization/+page.svelte
  tumi-mundo/src/routes/statistics/+page.svelte
  tumi-mundo/static/lib/styles/style.css
  tumi-mundo/vite.config.js
Labels: hhahahah (✿◠‿◠), feat 𓃀, fix 🔫, adorable :sparkles:

#26 FEATURE: timer with face detection working
  tumi-mundo/src/routes/attentiontest/+page.svelte
Labels: feat 𓃀, adorable :sparkles:

#30 ADD: face tracking with camera
  tumi-mundo/src/routes/attentiontest/+page.svelte
Labels: style ₊⊹⋆⁺, feat 𓃀

#36 FIX: Routes skip customization, back button accessible over popups
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/onboarding/+page.svelte
Labels: fix 🔫

#37 ADD: Audiofiles
  tumi-mundo/static/lib/audios/HF-list1.wav
  tumi-mundo/static/lib/audios/LF-list 1.wav
Labels: bffr (ノಠ益ಠ)ノ彡┻━┻, hhahahah (✿◠‿◠)

#39 FEAT: Progress bar with high frequency audio
  tumi-mundo/src/routes/attentiontest/+page.svelte
Labels: hhahahah (✿◠‿◠), brother ewwwww (。≖ˇ益ˇ≖｡), feat 𓃀, i'm s̴͓̙͓͑͆̚a̵͙͔̦̒͌͝d̵̫͔̟̿̓͆

#43 FEAT: Redirect to statistics page after the test is completed
  tumi-mundo/src/routes/+page.svelte
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/src/routes/offboarding/+page.svelte
Labels: feat 𓃀

#44 FEAT: Check your baby before the test
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺, feat 𓃀, fix 🔫

#45 ADD: Vercel deployment configuration
  tumi-mundo/vercel.json
Labels: feat 𓃀

#46 starting with d3 - line graph
  tumi-mundo/package-lock.json
  tumi-mundo/package.json
  tumi-mundo/src/components/LineChart.svelte
  tumi-mundo/src/routes/statistics/+page.svelte
Labels: hhahahah (✿◠‿◠), brother ewwwww (。≖ˇ益ˇ≖｡), i'm s̴͓̙͓͑͆̚a̵͙͔̦̒͌͝d̵̫͔̟̿̓͆, unfortune ¯\_(ツ)_/¯

#52 FIX: Progress bar causing blank spaces in body
  tumi-mundo/src/routes/attentiontest/+page.svelte
  tumi-mundo/static/lib/styles/style.css
Labels: fix 🔫

#57 STYLE/FIX: Accordion and modules grow until breakpoint
  tumi-mundo/static/lib/styles/style.css
Labels: style ₊⊹⋆⁺

#59 ADD/FIX: Line chart work with 5 data like 4
  tumi-mundo/src/components/LineChart.svelte
Labels: feat 𓃀, adorable :sparkles:
